# Generated by Django 4.2.3 on 2023-07-13 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='Produto',
            new_name='produto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='nome',
        ),
    ]
