# Generated by Django 4.2.3 on 2023-07-14 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_pedido_payment_intent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='payment_intent',
        ),
    ]
